/* Action types */

export const CHANGE_HANDBOOK_PAGE = 'CHANGE_HANDBOOK_PAGE';
export const PERFORM_USER_LOGIN = "PERFORM_USER_LOGIN";
export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';
export const USER_NOT_AUTHENTICATED = 'USER_NOT_AUTHENTICATED';
export const LOGOUT_USER = 'LOGOUT_USER';
export const USER_UPSERT = 'USER_UPSERT';


export const FETCH_USER = 'fetch_user';

